# Generated by Django 5.1 on 2024-09-15 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment_post_blog_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='blog_post',
            new_name='post',
        ),
        migrations.RemoveField(
            model_name='post',
            name='blog_comments',
        ),
    ]
