# Generated by Django 5.1 on 2024-09-23 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_category_alter_tag_name_alter_post_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': [('can_edit_post', 'Can edit post'), ('can_publish_post', 'Can publish post'), ('can_view_post', 'Can view post')]},
        ),
    ]
