# Generated by Django 5.1 on 2024-09-02 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_task_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('1', 'Faible'), ('2', 'Moyenne'), ('3', 'Élevée')], default='1', max_length=10),
        ),
    ]
