# Generated by Django 5.1 on 2024-09-02 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('personal', 'Personnel'), ('work', 'Travail'), ('other', 'Autre')], default='personal', max_length=20),
        ),
    ]
